version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: memory-garden-db
    environment:
      POSTGRES_DB: memory_garden
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Memory Garden Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memory-garden-app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/memory_garden
      - NEXTAUTH_SECRET=your-nextauth-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  # Redis (Optional - for session storage)
  redis:
    image: redis:7-alpine
    container_name: memory-garden-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 